Buscando_Mi_Trago_Web/Models/ErrorViewModel.cs
namespace Buscando_Mi_Trago_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Buscando_Mi_Trago_Web/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Buscandomitrago.Domain;
using Buscandomitrago.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Buscandomitrago.Domain.Utils;
using Buscandomitrago.Application.IServices;
using Microsoft.AspNetCore.JsonPatch.Internal;
namespace Buscando_Mi_Trago_Web.Controllers
{
    public class ApiController : Controller
    {
        private readonly IApiService _apiService;

        public ApiController(IApiService apiService)
        {
            _apiService = apiService;
        }


        [HttpPost]
        public async Task<IActionResult> CreateDrink([FromBody] Drink drink)
        {
            await _apiService.CreateDrink(drink);
            return StatusCode(200);
        }

        [HttpGet]
        public  JsonResult GetMydrinks()
        {
           List<DrinksView> myDrinks =  _apiService.GetMydrinks();
            return Json(myDrinks);
        }
    }
}

Buscando_Mi_Trago_Web/Controllers/HomeController.cs
using Buscando_Mi_Trago_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Buscando_Mi_Trago_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Buscando_Mi_Trago_Web/Controllers/MyDrinksController.cs
using Microsoft.AspNetCore.Mvc;

namespace Buscando_Mi_Trago_Web.Controllers
{
    public class MyDrinksController : Controller
    {
        public IActionResult MyList()
        {
            return View();
        }
    }
}

Buscando_Mi_Trago_Web/Views/Home/Index.cshtml
@using System.Web.Optimization

@{
    ViewBag.Title = "Buscando mi Trago";
}
<style>
    .container {
        margin-top: 20px;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td {
        width: 100px;
        text-align: center;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody td {
        word-wrap: break-word;
        white-space: normal;
    }

    .btnName {
        background-color: #F9502D;
        color: white;
        border: 3px;
        padding: 8px 15px;
        font-size: 16px;
        border-radius: 9px;
        text-align: center;
    }

    .btnIngredient {
        background-color: #F69A19;
        color: white;
        border: 3px;
        padding: 8px 15px;
        font-size: 16px;
        border-radius: 9px;
        text-align: center;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td,
    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table thead th {
        text-align: center;
    }

        .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td img,
        .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td button {
            display: block;
            margin: 0 auto;
        }

    .vertical-align {
        vertical-align: middle !important;
        text-align: center;
    }


    .borderSearch {
        border-radius: 5px;
    }

    .text-color {
        color: #d30f0d;
    }

    #searchDrink {
        font-family: sans-serif;
        padding-left: 9px;
        padding-right: 9px;
    }
</style>



<div class="wrapper wrapper-content animated fadeInRight">
    <br />
    <div class="row m-b-lg">
        <div class="col-lg-12">
            <div class="text-center">
                <img src="~/images/logo.png" />
            </div>
        </div>
        <div class="col-lg-12">
            <div class="text-center loginscreen ">
                <br />

                <h2 class="text-center">Welcome to <span class="text-color">Buscando mi trago</span></h2>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="text-center">
            <div class="form-group">
                <input type="text" id="searchDrink" class="col-lg-3 borderSearch" style=" margin-bottom: 10px;" placeholder="Search:">
            </div>
            <button id="searchByName" class="btnName" onclick="Search('1', document.getElementById('searchDrink').value)">Search by name</button>
            <button id="searchByIngredient" class="btnIngredient" onclick="Search('2', document.getElementById('searchDrink').value)">Search by ingredient</button>
        </div>
    </div>
</div>
<div class="col-lg-12">
    <div class="ibox ">
        <div class="ibox-content">
            <table data-page-size="10" id="lstDrink" class="table table-striped table-condensed display responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Instructions</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/sweetalert.css" />
}

@section Scripts {
    <script src="~/lib/datatables/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/datatables/dataTables.responsive.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>


    <script>
        var table;
        var URL;
        var drinks;
        function loadTableDrink() {
            table = $('#lstDrink').DataTable({
                ajax: function (data, callback, settings) {
                    $.ajax({
                        url: URL,
                        method: "GET",
                        success: function (result, textStatus, jQxhr) {
                            drinks = result.drinks;
                            callback({
                                data: drinks,
                            });
                        },
                        error: function (jqXhr, textStatus, errorThrown) {
                            console.error("Error al realizar la solicitud:", errorThrown);
                        }
                    });
                },

                columns: [
                    {
                        "data": "strDrinkThumb",
                        "className": "vertical-align",
                        "responsivePriority": 1,
                        "render": function (data, type, row) {
                            return `<img src="${data}" alt="Drink Thumbnail" style="width: 200px; height: 200px;">`;
                        }
                    },
                    { "data": "strDrink", "className": "vertical-align", "responsivePriority": 1 },
                    {
                        "data": "strInstructions",
                        "className": "vertical-align",
                        "responsivePriority": 1,
                        "render": function (data, type, row) {
                            return `<div style=" word-wrap: break-word; white-space: normal;">${data}</div>`;
                        }
                    },
                    {
                        "data": null,
                        "responsivePriority": 1,
                        "className": "vertical-align",
                        "render": function (data, type, row) {
                            return `<button class="btnName" onclick="addDrink('${row.idDrink}')">Add</button>`;
                        }
                    }
                ],
                responsive: true,
                paging: false,
                order: false,
                searching: false,
                ordering: false,
                info: "",
            });
        }

        function Search(Action, searchDrink) {
            if (!table) {
                loadTableDrink();
            }
            if (Action === '1') {
                URL = 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s=' + searchDrink;
            } else {
                URL = 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=' + searchDrink;
            }
            $('#lstDrink').DataTable().ajax.reload();
        }

        function addDrink(DrinkId) {
            const drink = drinks.find(d => d.idDrink === DrinkId);
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CreateDrink", "API")',
                data: JSON.stringify(drink),
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    swal({
                        title: "Success",
                        text: "Drink added to your list",
                        icon: "success",
                        button: "OK",
                    });
                },
                error: function (xhr, status, error) {
                    console.error("AJAX error:", status, error);
                }
            });
        }

    </script>
}

Buscando_Mi_Trago_Web/Views/MyDrinks/MyList.cshtml
<style>

    .custom-column-width {
        width: 357px !important;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td {
        width: 100px;
        text-align: center;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody td {
        word-wrap: break-word;
        white-space: normal;
    }

    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td,
    .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table thead th {
        text-align: center;
    }

        .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td img,
        .dataTables_wrapper .dataTables_scroll .dataTables_scrollBody table tbody td button {
            display: block;
            margin: 0 auto;
        }
</style>


<div class="wrapper wrapper-content animated fadeInRight">
    <br />
    <div class="row m-b-lg">
        <div class="col-lg-12">
            <div class="text-center">
                <img src="~/images/logo.png" />
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12">
    <div class="ibox ">
        <div class="ibox-content">
            <table data-page-size="10" id="lstMyDrinks" class="table table-striped table-condensed display responsive" style="width:100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Ingredients</th>
                        <th>Instructions</th>
@*                         <th>Action</th> *@
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/sweetalert.css" />
}

@section Scripts {
    <script src="~/lib/datatables/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/datatables/dataTables.responsive.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>

    <script>
        var drinks;
        $(document).ready(function () {
            loadTableDrink();
        });

        function loadTableDrink() {
            table = $('#lstMyDrinks').DataTable({
                ajax: function (data, callback, settings) {
                    $.ajax({
                        url: '@Url.Action("GetMydrinks", "API")',
                        method: "GET",
                        success: function (result, textStatus, jQxhr) {
                            drinks = result;
                            callback({
                                data: drinks,
                            });
                        },
                        error: function (jqXhr, textStatus, errorThrown) {
                            console.error("Error al realizar la solicitud:", errorThrown);
                        }
                    });
                },
                columns: [
                    { "data": "strDrink" },
                    { "data": "ingredientsWithMeasures", "className": "custom-column-width" },
                    {
                        "data": "strInstructions", "render": function (data, type, row) {
                            return `<p style=" word-wrap: break-word; white-space: normal;">${data}</p>`;
                        }
                    },
                ],
                responsive: true,
                paging: true,
                order: false,
                searching: true,
                ordering: false ,
            });
        }
    </script>
}

Buscando_Mi_Trago_Web/Views/Shared/_Layout.cshtml
<style>
    body {
        background-color: #b39e9e;
    }
</style>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Buscando mi trago</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Buscando_Mi_Trago_Web.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyDrinks" asp-action="MyList">My drinks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>